### ISSUE TITLE
Outbounds: Proper data caching

### ISSUE THREAD

**Issue by HiptJo** [HiptJo/active-connect#71]
non-sensitive data should be cached on the device

hash value should ensure whether the data needs to be reloaded when the connection is established or not.

outbound should check whether data needs to be sent before transmitting the data

**Comment by HiptJo** [comment]
Data Caching is currently not supported for lazy-loaded outbounds

**Comment by HiptJo** [comment]
The client should be able to add to the `___cache` request that the data is already present (no restore command required)

**Comment by HiptJo** [comment]
value parsing is not correctly configured for testing-connection setup

error message:
```
    SyntaxError: Unexpected token o in JSON at position 1
        at JSON.parse (<anonymous>)
      at Function.parse (node_modules/src/json/json-parser.ts:42:19)
      at TC.<anonymous> (node_modules/src/integration-testing/connections/tc.ts:272:24)
      at fulfilled (node_modules/active-connect/integration-testing/connections/tc.js:5:58)
```
